tasks:
  - init: npm install && npm install -g @shower/cli && npm audit fix
    command: Ñ‚npm run dev
  
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - garytyler.darcula-pycharm
